---
title: "Story 2"
author: "Andrew Bowen"
date: "2023-09-16"
output: pdf_document
---
# Story 2

```{r setup, include=FALSE}
library(tidyverse)
library(httr)
library(jsonlite)
library(glue)
```


## Data Sources

- [New York Fed API](https://markets.newyorkfed.org/static/docs/markets-api.html#/)
- [BLS Data API](https://www.bls.gov/developers/api_signature_v2.htm#single) - used for unemployment data

The BLS API has an [R wrapper](https://www.bls.gov/developers/api_r.htm) that allows for easy data pulls from the API.


```{r}
url <- "https://api.bls.gov/publicAPI/v2/timeseries/popular?survey=AP"
response <- GET(url)

response_txt <- content(response, "text", encoding = "UTF-8")
json <- fromJSON(response_txt)

json
```
## Getting CPI time series data

```{r get cpi-time-series}
# Call CPI data from BLS
registration_key <- Sys.getenv("BLS_API_KEY")
series_id <- 'APU0000706111'
series_url <- glue("https://api.bls.gov/publicAPI/v2/timeseries/data/{series_id}?registrationky={registration_key}&startyear=2013&endyear=2023")

response <- GET(series_url)
```

```{r}
# Format CPI data
response_txt <- content(response, "text", encoding = "UTF-8")
json <- fromJSON(response_txt, flatten = TRUE)

cpi <- as.data.frame(json[[4]])$series.data
```